Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 1070, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 897, in resolve
    dist = self._resolve_dist(
        req, best, replace_conflicting, env, installer, required_by, to_activate
    )
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 943, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (blinker 1.8.2 (/usr/lib/python3.13/site-packages), Requirement.parse('blinker>=1.9'), {'Flask', 'flask'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/voltron", line 33, in <module>
    sys.exit(load_entry_point('voltron==0.1.7', 'console_scripts', 'voltron')())
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/voltron", line 25, in importlib_load_entry_point
    return next(matches).load()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/importlib/metadata/__init__.py", line 179, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.13/site-packages/voltron/__init__.py", line 6, in <module>
    from .main import main
  File "/usr/lib/python3.13/site-packages/voltron/main.py", line 9, in <module>
    from .view import *
  File "/usr/lib/python3.13/site-packages/voltron/view.py", line 25, in <module>
    from .core import Client
  File "/usr/lib/python3.13/site-packages/voltron/core.py", line 25, in <module>
    from .api import *
  File "/usr/lib/python3.13/site-packages/voltron/api.py", line 15, in <module>
    from scruffy.plugin import Plugin
  File "/usr/lib/python3.13/site-packages/scruffy/__init__.py", line 1, in <module>
    from .env import Environment
  File "/usr/lib/python3.13/site-packages/scruffy/env.py", line 17, in <module>
    from .file import Directory
  File "/usr/lib/python3.13/site-packages/scruffy/file.py", line 15, in <module>
    import pkg_resources
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3672, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3656, in _call_aside
    f(*args, **kwargs)
    ~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3685, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 897, in resolve
    dist = self._resolve_dist(
        req, best, replace_conflicting, env, installer, required_by, to_activate
    )
  File "/usr/lib/python3.13/site-packages/pkg_resources/__init__.py", line 938, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blinker>=1.9' distribution was not found and is required by Flask, flask
